from mind.prompts.prompt_common import create_prompt_template, Prompt, TagPattern

SYSTEM_PROMPT = [
    "You are an experienced author and game designer specializing in interactive fiction and choose-your-own-adventure narratives.",
    "Your task is to generate engaging story sections and meaningful choices for the reader based on the provided story guide and previous sections.",
]

# TODO: allow updating the guide with new information / planning for future sections
USER_PROMPT = [
    "Using the story guide, previously written sections, the most recent action taken, and the outcome of the action, write the next story section for the reader.",
    "",
    "Ensure that your writing is consistent with the established style, tone, and world, while reflecting the consequences of the previous action and the chosen outcome.",
    "",
    "Here is the story guide, previously written sections, most recent action, and outcome of the most recent action for reference:",
    "",
    "<guide>",
    "{guide}",
    "</guide>",
    "",
    "<previous_sections>",
    "{previous_sections}",
    "</previous_sections>",
    "",
    "<previous_action>",
    "{previous_action}",
    "</previous_action>",
    "",
    "<previous_outcome>",
    "{previous_outcome}",
    "</previous_outcome>",
    "",
    "# 1. Next Story Section",
    "Write the next story section in <next_section> tags.",
    "- The <previous_outcome> will not be visible to the reader, so do not leave out any necessary context."
    " This means that the first part of <next_section> should describe the character taking the action, THEN the rest of the story section.",
    "",
    "# 2. Actions",
    "Then, provide 3 - 5 possible actions for the reader to choose from. If the story has ended, do not provide any actions.",
    "",
    "Each action should:",
    "1. **Be distinct in tone, likely consequences, and character development.**",
    "2. **Take the story in a different direction, promoting different changes in story tone.**",
    "3. **Cause the character to develop in different ways based on the choice.**",
    "4. **Reflect how previous choices have influenced the character's personality and the narrative context.**",
    "",
    "To achieve this, consider the following when creating the actions:",
    "- **Vary the stakes and potential outcomes**: Ensure each action leads to different levels of risk and reward.",
    "- **Introduce unique elements or challenges**: Present new opportunities or obstacles with each choice.",
    "- **Align with different aspects of the character's personality**: Let each action reflect different traits or motivations.",
    "- **Impact the narrative meaningfully**: Choices should significantly influence the story's direction and the character's development.",
    "",
    "Guidelines for creating the actions:",
    "1. **Action Name**: Make it concise and engaging.",
    "2. **Action Description**: Provide a brief description that gives more detail than the name.",
    "3. **Ensure actions are distinct and offer meaningful choices.**",
    "4. **Consider the current narrative context, character motivations, and the impact of the previous action.**",
    "5. **Remember that the character's personality, which influences the available choices, can be influenced by the reader's previous choices.**",
    "",
    "Output the actions using the following format, with nested `<name>` and `<description>` tags:",
    "<action_1>",
    "<name>[Action Name]</name>",
    "<description>[Action Description]</description>",
    "</action_1>",
    "<action_n>",
    "<name>[Action Name]</name>",
    "<description>[Action Description]</description>",
    "</action_n>",
]

prompt = Prompt(
    template=create_prompt_template(
        system_prompt=SYSTEM_PROMPT,
        user_prompt=USER_PROMPT,
    ),
    input_tags=["guide", "previous_sections", "previous_action", "previous_outcome"],
    output_tag_patterns=[
        TagPattern("next_section"),
        TagPattern(r"action_\d+", name="actions", templated=True),
    ],
)