from npc.prompts.prompt_common import create_prompt_template, Prompt, TagPattern

SYSTEM_PROMPT = [
    "You are an experienced author and game designer specializing in interactive fiction and choose-your-own-adventure narratives.",
    "Your task is to generate engaging story sections and meaningful choices for the reader based on the provided story guide and previous sections.",
]

# TODO: allow updating the guide with new information / planning for future sections
USER_PROMPT = [
    "# Creating Multiple Outcomes for Choose Your Own Adventure",
    "",
    "## Context and References",
    "Using the story guide, previously written sections, and the most recent action taken, create multiple possible outcomes for the next part of the interactive story.",
    "Ensure that your writing is consistent with the established style, tone, and world, while reflecting the consequences of the chosen action.",
    "Provide meaningful outcomes that advance the plot and consider the impact of previous decisions.",
    "",
    "Here is the story guide, previously written sections, and the most recent action for reference. Make sure to adhere to the story guide.",
    "<guide>",
    "{guide}",
    "</guide>",
    "",
    "<previous_sections>",
    "{previous_sections}",
    "</previous_sections>",
    "",
    "<previous_action>",
    "{previous_action}",
    "</previous_action>",
    "",
    "## Outcome Generation Guidelines",
    "Generate 3 - 5 possible outcomes for the story. For each outcome, include the following:",
    "",
    "1. **Outcome Description**: Briefly describe the outcome and its implications for the story. Keep each description to 30 words or less.",
    "2. **Likelihood**: Assign a likelihood value to the outcome based on its plausibility within the story context. These values will be used to randomly sample an outcome (after being processed through a softmax function to create a probability distribution).",
    "3. **Ends Story**: Indicate whether the outcome concludes the story (`True`) or if it should continue (`False`).",
    "",
    "## Key Principles",
    "- The character's intent and actions should remain consistent across all outcomes, based on a reasonable interpretation of the <previous_action>.",
    "- Variations between outcomes should arise from external factors, chance events, or how the world responds to the character's action.",
    "- This approach ensures that the reader's choices meaningfully impact the story while maintaining the integrity of character decisions.",
    "",
    "## Diversity of Outcomes",
    "Include a diverse range of outcomes, such as:",
    "- The character's action succeeding as intended",
    "- Partial success with unexpected complications",
    "- Unintended consequences despite the character's best efforts",
    "- External factors interfering with or altering the results of the action",
    "- Low-probability but interesting outcomes that could take the story in unexpected directions",
    "",
    "Aim for a balance of positive, negative, and neutral outcomes. Include outcomes that open up new story possibilities as well as those that narrow the plot. This variety will keep the story engaging and unpredictable.",
    "",
    "## Pacing and Story Structure",
    "Consider pacing and story structure when creating outcomes:",
    "- Balance short-term consequences with long-term plot development.",
    "- Some outcomes should advance the main plot, while others might explore side plots or character development.",
    "- Vary the intensity of outcomes to create a rhythm in the story's pacing.",
    "",
    "## Incorporating Previous Choices",
    "Carefully consider how previous reader choices influence the current set of outcomes:",
    "- Ensure that the range of possible outcomes reflects decisions made earlier in the story.",
    "- Create callbacks or consequences to earlier choices to make the story feel cohesive and responsive.",
    "- Use previous decisions to inform the likelihood of certain outcomes.",
    "",
    "## Likelihood and Story Endings",
    "The likelihood should reflect how reasonable the outcome is given the context of the story, the character's actions, and previous reader choices. After the first couple of actions, it should be common for one or more of the outcomes to end the story.",
    "",
    "An outcome should end the story if:",
    "1. The subsequent story will reach a natural conclusion or the main conflict is resolved.",
    "2. It reflects the main character failing to achieve their goal due to external circumstances.",
    "3. The subsequent story will reach a point where further choices are unnecessary, redundant, or repetitive.",
    "",
    "## Formatting Instructions",
    "Use the following format for each outcome:",
    "",
    "<outcome_1>",
    "[Your outcome description here, 30 words or less]",
    "</outcome_1>",
    "<likelihood_1>",
    "[Likelihood value as a number]",
    "</likelihood_1>",
    "<ends_story_1>",
    "[True or False]",
    "</ends_story_1>",
    "",
    "...",
    "",
    "<outcome_n>",
    "[Your outcome description here, 30 words or less]",
    "</outcome_n>",
    "<likelihood_n>",
    "[Likelihood value as a number]",
    "</likelihood_n>",
    "<ends_story_n>",
    "[True or False]",
    "</ends_story_n>",
]

prompt = Prompt(
    template=create_prompt_template(
        system_prompt=SYSTEM_PROMPT,
        user_prompt=USER_PROMPT,
    ),
    input_tags=["guide", "previous_sections", "previous_action"],
    output_tag_patterns=[
        TagPattern(r"outcome_\d+", name="outcomes", templated=True),
        TagPattern(r"likelihood_\d+", name="likelihoods", templated=True),
        TagPattern(r"ends_story_\d+", name="ends_stories", templated=True),
    ],
)